export const _course = {
  id: 1,
  name: "Learn DevOps: The Complete Kubernetes Course",
  category_name: "Learn DevOps: The Complete Kubernetes Course",
  rating: 4.5,
  ratings: 1445,
  students: 22301,
  price: 339.99,
  sale_price: 229.99,
  image: null,
  best_seller: true,
  new: false,
  last_update: "22/05/2021",
  short_description:
    "Nostrud elit nostrud exercitation dolore esse officia adipisicing est ipsum sint eiusmod duis.",
  full_description:
    "Lorem deserunt magna minim nulla aute irure irure. Sit in irure exercitation nostrud anim excepteur. Mollit tempor ipsum occaecat adipisicing.Lorem deserunt magna minim nulla aute irure irure. Sit in irure exercitation nostrud anim excepteur. Mollit tempor ipsum occaecat adipisicing.Lorem deserunt magna minim nulla aute irure irure. Sit in irure exercitation nostrud anim excepteur. Mollit tempor ipsum occaecat adipisicing.",
  teacher_name: "Edward Viaene",
  teacher_id: 1,
  teacher_expert: "DevOps, Cloud, Big Data Specialist",
  teacher_rating: 4.5,
  teacher_ratings: 200,
  teacher_courses: 20,
  teacher_students: 20000,
  teacher_reviews: 2000,
  teacher_description:
    "I've been a System Administrator and full stack developer for over 10 years, the typical profile for a DevOps engineer. I've been working in multiple organizations and startups. I've cofounded a startup that focusses on applying DevOps and Cloud. I have been training people in newer technologies, like Big Data. I've trained a lot of people working in FTSE 100 & S&P 100 companies. Today I mainly work together with companies to improve their software delivery processes, while coaching and teaching on platforms like Udemy.",
  sections: [
    {
      id: 1,
      stt: 1,
      name: "Course Introduction",
      lectures: [
        {
          id: 1,
          stt: 1,
          name: "Course Introduction",
          link: "www.youtube.com/watch?v=FLGCGc7sAUw",
          preview: true,
          duration: 2 * 60 + 50,
        },
        {
          id: 2,
          stt: 2,
          name: "Support and Course Material",
          link: "www.youtube.com/watch?v=FLGCGc7sAUw",
          preview: true,
          duration: 2 * 60 + 50,
        },
      ],
    },
    {
      id: 2,
      stt: 2,
      name: "Introduction to Kubernetes",
      lectures: [
        {
          id: 1,
          stt: 1,
          name: "Course Introduction",
          link: "www.youtube.com/watch?v=FLGCGc7sAUw",
          preview: false,
          duration: 2 * 60 + 50,
        },
        {
          id: 2,
          stt: 2,
          name: "Support and Course Material",
          link: "www.youtube.com/watch?v=FLGCGc7sAUw",
          preview: false,
          duration: 2 * 60 + 50,
        },
        {
          id: 3,
          stt: 3,
          name: "Kubernetes Introduction",
          link: "www.youtube.com/watch?v=FLGCGc7sAUw",
          preview: false,
          duration: 2 * 60 + 50,
        },
      ],
    },
    {
      id: 3,
      stt: 3,
      name: "Kubernetes Basics",
      lectures: [
        {
          id: 1,
          stt: 1,
          name: "Course Introduction",
          link: "www.youtube.com/watch?v=FLGCGc7sAUw",
          duration: 2 * 60 + 50,
          preview: false,
        },
        {
          id: 2,
          stt: 2,
          name: "Support and Course Material",
          link: "www.youtube.com/watch?v=FLGCGc7sAUw",
          preview: false,
          duration: 2 * 60 + 50,
        },
      ],
    },
  ],
  rating_chart: [
    {
      type: 1,
      ratings: 185,
    },
    {
      type: 2,
      ratings: 0,
    },
    {
      type: 3,
      ratings: 120,
    },
    {
      type: 4,
      ratings: 320,
    },
    {
      type: 5,
      ratings: 820,
    },
  ],
};

export const _courses = [
  {
    id: 1,
    name: "Complete Web Developer Training",
    teacher_name: "John Taylor",
    teacher_id: 1,
    category_name: "Web Development",
    rating: 4.5,
    ratings: 1145,
    students: 22301,
    price: 339.99,
    sale_price: 229.99,
    image: null,
    best_seller: true,
    new: false,
  },
  {
    id: 2,
    name: "Complete Web Developer Training",
    teacher_name: "John Taylor",
    teacher_id: 1,
    category_name: "Web Development",
    rating: 4.5,
    ratings: 1145,
    students: 22301,
    price: 339.99,
    sale_price: 229.99,
    image: null,
    best_seller: false,
    new: true,
  },
  {
    id: 3,
    name: "Complete Web Developer Training",
    teacher_name: "John Taylor",
    teacher_id: 1,
    category_name: "Web Development",
    rating: 4.5,
    ratings: 1145,
    students: 22301,
    price: 339.99,
    sale_price: 229.99,
    image: null,
    best_seller: false,
    new: true,
  },
  {
    id: 4,
    name: "Complete Web Developer Training",
    teacher_name: "John Taylor",
    teacher_id: 1,
    category_name: "Web Development",
    rating: 4.5,
    ratings: 1145,
    students: 22301,
    price: 339.99,
    sale_price: null,
    image: null,
    best_seller: false,
    new: false,
  },
  {
    id: 5,
    name: "Complete Web Developer Training",
    teacher_name: "John Taylor",
    teacher_id: 1,
    category_name: "Web Development",
    rating: 4.5,
    ratings: 1145,
    students: 22301,
    price: 339.99,
    sale_price: 229.99,
    image: null,
    best_seller: false,
    new: true,
  },
  {
    id: 6,
    name: "Complete Web Developer Training",
    teacher_name: "John Taylor",
    teacher_id: 1,
    category_name: "Web Development",
    rating: 4.5,
    ratings: 1145,
    students: 22301,
    price: 339.99,
    sale_price: null,
    image: null,
    best_seller: false,
    new: true,
  },
  {
    id: 7,
    name: "Complete Web Developer Training",
    teacher_name: "John Taylor",
    teacher_id: 1,
    category_name: "Web Development",
    rating: 4.5,
    ratings: 1145,
    students: 22301,
    price: 339.99,
    sale_price: 229.99,
    image: null,
    best_seller: false,
    new: false,
  },
  {
    id: 8,
    name: "Complete Web Developer Training",
    teacher_name: "John Taylor",
    teacher_id: 1,
    category_name: "Web Development",
    rating: 4.5,
    ratings: 1145,
    students: 22301,
    price: 339.99,
    sale_price: 229.99,
    image: null,
    best_seller: false,
    new: false,
  },
  {
    id: 9,
    name: "Complete Web Developer Training",
    teacher_name: "John Taylor",
    teacher_id: 1,
    category_name: "Web Development",
    rating: 4.5,
    ratings: 1145,
    students: 22301,
    price: 339.99,
    sale_price: 229.99,
    image: null,
    best_seller: false,
    new: false,
  },
  {
    id: 10,
    name: "Complete Web Developer Training",
    teacher_name: "John Taylor",
    teacher_id: 1,
    category_name: "Web Development",
    rating: 4.5,
    ratings: 1145,
    students: 22301,
    price: 339.99,
    sale_price: 229.99,
    image: null,
    best_seller: false,
    new: false,
  },
  {
    id: 11,
    name: "Complete Web Developer Training",
    teacher_name: "John Taylor",
    teacher_id: 1,
    category_name: "Web Development",
    rating: 4.5,
    ratings: 1145,
    students: 22301,
    price: 339.99,
    sale_price: 229.99,
    image: null,
    best_seller: false,
    new: false,
  },
  {
    id: 12,
    name: "Complete Web Developer Training",
    teacher_name: "John Taylor",
    teacher_id: 1,
    category_name: "Web Development",
    rating: 4.5,
    ratings: 1145,
    students: 22301,
    price: 339.99,
    sale_price: 229.99,
    image: null,
    best_seller: false,
    new: false,
  },
];

export const _cats = [
  {
    id: 1,
    name: "Design",
    students: 656300,
  },
  {
    id: 2,
    name: "Development",
    students: 556300,
  },
  {
    id: 3,
    name: "Marketing",
    students: 456300,
  },
  {
    id: 4,
    name: "IT and software",
    students: 356300,
  },
  {
    id: 5,
    name: "Personal Development",
    students: 256300,
  },
  {
    id: 6,
    name: "Business",
    students: 156300,
  },
  {
    id: 7,
    name: "Photography",
    students: 56300,
  },
  {
    id: 8,
    name: "Music",
    students: 6300,
  },
];
